FROM node:5.5.0-slim

#create app directory

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# install dependencies

COPY package.json /usr/src/app/
RUN npm install

#bundle app source
COPY src /usr/src/app

EXPOSE 3000

CMD ["npm", "start"]


